services:
  cloudflare_ddns:
    image: conner0512/cloudflare_ddns:2.3 # 使用自定义构建的镜像
    container_name: cloudflare_ddns
    environment:
      API_TOKEN: axT1OtsrhjpSyAipelX3lSjMklRchA8fQcijJ5lt # 替换为你的 Cloudflare API Token
      ZONE_NAME: connerhome.org # 替换为你的域名
      DNS_RECORD_NAME: ddns.connerhome.org # 替换为你的子域名
      PROXIED: false # 是否启用 Cloudflare 的代理功能
    restart: unless-stopped
networks: {}
