services:
  cloudflare_ddns:
    image: conner0512/cloudflare_ddns:2.3
    container_name: cloudflare_ddns
    environment:
      API_TOKEN: ${CF_API_TOKEN}
      ZONE_NAME: connerhome.org
      DNS_RECORD_NAME: ddns.connerhome.org
      PROXIED: false
    restart: unless-stopped
networks: {}
