
services:
  meshcentral:
    image: ghcr.io/ylianst/meshcentral:master
    container_name: meshcentral
    ports:
      - "10443:443"
      - "18080:80"
    volumes:
      - /Users/weilu/Docker/meshcentral/data:/opt/meshcentral/meshcentral-data    #config.json and other important files live here. A must for data persistence
      - /Users/weilu/Docker/meshcentral/user_files:/opt/meshcentral/meshcentral-files    #where file uploads for users live
      - /Users/weilu/Docker/meshcentral/backups:/opt/meshcentral/meshcentral-backups     #Backups location
    restart: always